<?php

namespace FIRST\JeuBundle\Repository;

/**
 * defausseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class defausseRepository extends \Doctrine\ORM\EntityRepository
{
}
