<?php

namespace FIRST\JeuBundle\Repository;

/**
 * Position_SalonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Position_SalonRepository extends \Doctrine\ORM\EntityRepository
{
}
