<?php

namespace FIRST\JeuBundle\Repository;

/**
 * Position_salon_idRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Position_salon_idRepository extends \Doctrine\ORM\EntityRepository
{
}
