<?php

namespace FIRST\JeuBundle\Repository;

/**
 * Salon_joueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Salon_joueurRepository extends \Doctrine\ORM\EntityRepository
{
}
